### ISSUE TITLE
Masking input for GPT

### ISSUE THREAD

**Issue by RuslanOm** [isl-org/DPT#35]
Hello! 

Is it possible to mask input image for gpt? For example, I want to mask some trademarks, because I thinks, that this thing may influence on final depth map. Thanks!

**Comment by RuslanOm** [comment]
P.S. I tried to mask this in simple way (set not interested pixels to [0, 0, 0]), but model still uses this for prediction

**Comment by ranftlr** [comment]
The network is always using all pixels in the image, so if you mask any part of the input it will influence the results. Watermarks also influence the results. You could try to do some inpainting before feeding to the model. See here for recent methods: https://paperswithcode.com/task/image-inpainting
