### ISSUE TITLE
Training script for DPT

### ISSUE THREAD

**Issue by priyeshshukla** [isl-org/DPT#60]
Hello, this is a very good repository. If the training script can be made available as well, preferably as soon as possible, lot of follow up research outcomes can happen on the basis of this repo and papers. Requesting to please upload the training script as well. Thanks in advance!

**Comment by yassineAlouini** [comment]
@priyeshshukla There is this issue with a similar discussion: https://github.com/isl-org/DPT/issues/3
However, no plan yet (I guess the authors are busy).

**Comment by antocad** [comment]
@priyeshshukla We have re-implemented the paper presented in this repository, and we have added a training script. Check it out here: https://github.com/antocad/FocusOnDepth

**Comment by priyeshshukla** [comment]
@antocad Thanks! I will check it out.
