### ISSUE TITLE
Interpret a depth

### ISSUE THREAD

**Issue by dimasheva1** [isl-org/DPT#62]
How to convert a depth to real distance?

**Comment by dimasheva1** [comment]
Thank you for the answer! Good luck)

**Comment by fangli333** [comment]
Hi,

I have a question. You said that the predicted depth requires scale and shift to the real distance. so assume predicted depth is x, and i can use ax + b to model the real depth. And my question is does it mean, for each frame, it has its own a and b, or for all the frames of one processed video, they share the same a and b? a represent the scale, and b represent the shift.

Thank you.
