### ISSUE TITLE
Unit of the Absolute Depth

### ISSUE THREAD

**Issue by mohanhanmo** [isl-org/DPT#63]
Thank you very much for your awesome work first. I am just wondering, what is the unit/metrics of the predicted absolute depth? Is it in meter? Thanks!

**Comment by laihuaijing** [comment]
> Thank you very much for your awesome work first. I am just wondering, what is the unit/metrics of the predicted absolute depth? Is it in meter? Thanks!

Did you solve it? How should I get the actual distance from the estimated depth map? thanks ！

`if model_type == "dpt_large":
    net_w==net_h=384
    model=DPTDepthModel(
        path=model_path,
        bachbone="vitl16_384",
        non_negative=True,
        enable_attention_hooks=False,
    )
`

**Comment by dimasheva1** [comment]
Please, refer to #62. Hope it helps

**Comment by laihuaijing** [comment]
> Please, refer to #62. Hope it helps

Thank you!

**Comment by mohanhanmo** [comment]
> > Thank you very much for your awesome work first. I am just wondering, what is the unit/metrics of the predicted absolute depth? Is it in meter? Thanks!
> 
> Did you solve it? How should I get the actual distance from the estimated depth map? thanks ！
> 
> `if model_type == "dpt_large": net_w==net_h=384 model=DPTDepthModel( path=model_path, bachbone="vitl16_384", non_negative=True, enable_attention_hooks=False, ) `


By setting the flag of "--absolute_depth", the output will be the absolute depth without normalization. But I am not sure about the definition of "absolute depth" compared to the normalized depth

**Comment by mohanhanmo** [comment]
> > Please, refer to #62. Hope it helps

> Thank you!

Thank you very much

> Please, refer to #62. Hope it helps



> Please, refer to #62. Hope it helps

Thank you very much for your reply! If the output is scale and shift invariant and isn't linked to any real distance, then what is the difference between the absolute depth and the depth after normalization? Both of them should be scale and shift invariant, why dont we keep only the normalized output? Thanks!!

**Comment by matkovst** [comment]
> > Please, refer to #62. Hope it helps
> 
> Thank you very much for your reply! If the output is scale and shift invariant and isn't linked to any real distance, then what is the difference between the absolute depth and the depth after normalization? Both of them should be scale and shift invariant, why dont we keep only the normalized output? Thanks!!

The difference is that the absolute depth map preserves the real ratio between different depths (to the model accuracy, though), while normalized depth does not. 
Knowing correct scale α and shift β, you can estimate the real depth <img src="https://latex.codecogs.com/svg.image?D_{real}" title="D_{real}" />  in your unit system from the absolute depth map <img src="https://latex.codecogs.com/svg.image?D_{abs}" title="D_{abs}" /> applying <img src="https://latex.codecogs.com/svg.image?D_{real}=\alpha&space;D_{abs}&plus;\beta&space;" title="D_{real}=\alpha D_{abs}+\beta " />. On the other side, after applying normalization to your absolute depth map you lose the ability to estimate the real depth from this normalized map, because normalization is a non-linear operation. 
You may need to normalize depth in order to display it as a picture, like 
`cv::normalize(D_abs, D_normalized, 0.0, 255.0, cv::NORM_MINMAX, CV_8U);`
`cv::imshow("D_normalized", D_normalized);`

**Comment by mohanhanmo** [comment]
> > > Please, refer to #62. Hope it helps
> > 
> > 
> > Thank you very much for your reply! If the output is scale and shift invariant and isn't linked to any real distance, then what is the difference between the absolute depth and the depth after normalization? Both of them should be scale and shift invariant, why dont we keep only the normalized output? Thanks!!
> 
> The difference is that the absolute depth map preserves the real ratio between different depths (to the model accuracy, though), while normalized depth does not. Knowing correct scale α and shift β, you can estimate the real depth ![](https://camo.githubusercontent.com/bb8fcab585b0736823a83c313f4a6674b8cffee834dcc62a34aeed7278187961/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e696d6167653f445f7b7265616c7d) in your unit system from the absolute depth map ![](https://camo.githubusercontent.com/d274d1bbf648bc772979f21daf51f3b9361ceaa1da7c9d737f02a332dbd64f94/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e696d6167653f445f7b6162737d) applying ![](https://camo.githubusercontent.com/42a7ed311a48c6e2830a44cae9e536b8a898dfa3b5a9fe57100e2797e24a0c0d/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e696d6167653f445f7b7265616c7d3d5c616c7068612673706163653b445f7b6162737d2b5c626574612673706163653b). On the other side, after applying normalization to your absolute depth map you lose the ability to estimate the real depth from this normalized map, because normalization is a non-linear operation. You may need to normalize depth in order to display it as a picture, like `cv::normalize(D_abs, D_normalized, 0.0, 255.0, cv::NORM_MINMAX, CV_8U);` `cv::imshow("D_normalized", D_normalized);`

Thanks a lot for the explanation! That is very helpful. So it is saying that, even though we might not now the real distance based on absolute depth without scale and shift, but we can still compare the depth of 2 images by comparing their distance from the absolute foreground depth to the absolute background depth, right?

**Comment by matkovst** [comment]
> Thanks a lot for the explanation! That is very helpful. So it is saying that, even though we might not now the real distance based on absolute depth without scale and shift, but we can still compare the depth of 2 images by comparing their distance from the absolute foreground depth to the absolute background depth, right?

I'm not sure about 2 (different) images. Different scenes may have different scales and shifts. Given an image of some scene, you can calculate absolute distance from one object (at the front) to another object (in the back) in that scene and that will be proportional to the real distance between these two objects. You can also calculate the real distance if you know the underlying scale and shift for this particular scene. 
When you move to another image of another scene, there will be the second scale and shift, more likely different from the first ones.
