### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size

### ISSUE THREAD

**Issue by semel1** [isl-org/DPT#66]
Successfully run: 
`python run_monodepth.py -t dpt_large`

However attempt to run:
python run_monodepth.py (with dpt_hybrid (default) )

I've got an error:
`RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`

My great appreciation for help to resolving this issue.
How/where I should "Use .reshape(...) instead." As it suggests ?

**Comment by olegsinavski** [comment]
@semel1 I faced the same issue and it turned out that my `timm` version was older than DPT requires. After installing `timm==0.4.5` from the requirements, it all works now
